class LookbackError(Exception): ...

class DataError(LookbackError): ...
class SymbolNotFoundError(DataError): ...
class StaleCacheError(DataError): ...

class StrategyError(LookbackError): ...
class InvalidSignalError(StrategyError): ...

class BacktestError(LookbackError): ...
class InsufficientDataError(BacktestError): ...
class LookAheadBiasError(BacktestError): ...

class InvalidStateTransitionError(LookbackError): ...
class ConfigurationError(LookbackError): ...

